[package]
name = "srap"
version = "1.0.0"
authors = ["max <maximillain[at]disroot[dot]org>"]
edition = "2021"
rust_version = "1.74.0"
readme = "README.md"
repository = "https://github.com/cyborgcatboy/srap"
license = "GPL-3.0-or-later"
