.TH SRAP 1 2024-01-31 srap  

.SH NAME
.B srap
- the \fBs\fPhell \fBr\fPc \fBap\fPpender

.SH SYNOPSIS
.B srap 
[-a|--all] [-d|--dry-run] [-h|--help] [-n|--no-color] [-v|--verbose] 
.I line

.SH DESCRIPTION
Appends a given line to all POSIX-compliant shells, or the current shell. Includes a helper for the alias command, so you don't have to escape the quotation marks there, but you should in any other case!

.SH OPTIONS
.TP
.B -a, --all
Apply line to all POSIX-compatible shells

.TP
.B -d, --dry-run
Don't write to any files

.TP
.B -h, --help
Show the help message 

.TP
.B -n, --no-color
Program output will not include any ANSI escape sequences

.TP
.B -v, --verbose
Shows verbose program output

.SH COPYRIGHT
Copyright \(co 2024 max 74.25, meow at me about bugs at <maximillian[at]disroot[dot]org>

Licensed under the GNU GPLv3
